-- ==========================================================
-- Migration 001: Classroom/Student model + Beacon + Manual
-- attendance foundation columns.
--
-- SAFE / ADDITIVE ONLY:
--  - Every statement uses IF NOT EXISTS / ADD COLUMN IF NOT EXISTS
--  - No existing column is dropped, renamed, or retyped
--  - No existing row is modified except to receive a default value
--  - Safe to run multiple times (idempotent)
--
-- Run this against your Neon/PostgreSQL database BEFORE deploying
-- any backend code from folder 02 onward.
-- ==========================================================

-- --------------------------------------------------------
-- 1. Classrooms: beacon identity + active/inactive lifecycle
-- --------------------------------------------------------
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS bssid VARCHAR(100);
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE classrooms ADD COLUMN IF NOT EXISTS rssi_threshold INTEGER NOT NULL DEFAULT -85;
-- rssi_threshold: signal strength (dBm) below which a detected beacon is
-- considered "too far" to count as proximity. -85 is a safe default for
-- typical classroom-sized Wi-Fi coverage; Admin can tune per classroom.

COMMENT ON COLUMN classrooms.bssid IS 'Optional hardware MAC address (BSSID) of the classroom access point/beacon. Preferred over SSID when present because SSIDs can be duplicated by other networks.';
COMMENT ON COLUMN classrooms.is_active IS 'Deactivated classrooms are hidden from Teacher/Student dropdowns and cannot start new attendance sessions, but historical data is preserved.';

-- --------------------------------------------------------
-- 2. Explicit Student <-> Classroom membership
--    (Student -> Classroom -> Wi-Fi/Beacon relationship)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS classroom_students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    classroom_id INTEGER NOT NULL,
    student_id INTEGER NOT NULL,

    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (classroom_id)
        REFERENCES classrooms(id)
        ON DELETE CASCADE,

    FOREIGN KEY (student_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    UNIQUE(classroom_id, student_id)
);

CREATE INDEX IF NOT EXISTS idx_classroom_students_classroom ON classroom_students(classroom_id);
CREATE INDEX IF NOT EXISTS idx_classroom_students_student ON classroom_students(student_id);

-- --------------------------------------------------------
-- 3. Attendance Sessions: temporary beacon override support
--    (Teacher Hotspot / Nearby Wi-Fi options). These fields are
--    PER-SESSION ONLY and never overwrite classrooms.ssid/bssid.
-- --------------------------------------------------------
ALTER TABLE attendance_sessions ADD COLUMN IF NOT EXISTS beacon_type VARCHAR(20) NOT NULL DEFAULT 'CLASSROOM';
ALTER TABLE attendance_sessions ADD COLUMN IF NOT EXISTS override_ssid VARCHAR(100);
ALTER TABLE attendance_sessions ADD COLUMN IF NOT EXISTS override_bssid VARCHAR(100);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'attendance_sessions_beacon_type_check'
    ) THEN
        ALTER TABLE attendance_sessions
            ADD CONSTRAINT attendance_sessions_beacon_type_check
            CHECK (beacon_type IN ('CLASSROOM', 'HOTSPOT', 'NEARBY_WIFI'));
    END IF;
END $$;

COMMENT ON COLUMN attendance_sessions.beacon_type IS 'CLASSROOM = use classrooms.ssid/bssid (default). HOTSPOT = teacher device hotspot for this session only. NEARBY_WIFI = teacher-selected nearby network for this session only.';

-- --------------------------------------------------------
-- 4. Attendance Records: Automatic vs Manual + who marked it
--    + which beacon evidence was captured
-- --------------------------------------------------------
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS method VARCHAR(20) NOT NULL DEFAULT 'AUTOMATIC';
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS marked_by INTEGER;
ALTER TABLE attendance_records ADD COLUMN IF NOT EXISTS bssid VARCHAR(100);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'attendance_records_method_check'
    ) THEN
        ALTER TABLE attendance_records
            ADD CONSTRAINT attendance_records_method_check
            CHECK (method IN ('AUTOMATIC', 'MANUAL'));
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'attendance_records_marked_by_fkey'
    ) THEN
        ALTER TABLE attendance_records
            ADD CONSTRAINT attendance_records_marked_by_fkey
            FOREIGN KEY (marked_by) REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END $$;

COMMENT ON COLUMN attendance_records.method IS 'AUTOMATIC = student device auto-detected the beacon. MANUAL = a teacher overrode the record.';
COMMENT ON COLUMN attendance_records.marked_by IS 'Teacher user id who manually changed this record. NULL for automatic records.';

-- --------------------------------------------------------
-- 5. Backfill: seed classroom_students from the existing
--    implicit department+semester relationship so nothing
--    "loses" students the moment this migration runs.
--    (Safe to re-run: ON CONFLICT DO NOTHING)
-- --------------------------------------------------------
INSERT INTO classroom_students (classroom_id, student_id)
SELECT DISTINCT c.id, u.id
FROM classrooms c
JOIN class_subjects cs ON cs.classroom_id = c.id
JOIN subjects sub ON sub.id = cs.subject_id
JOIN users u ON u.department_id = sub.department_id AND u.semester = sub.semester
WHERE u.role = 'Student'
ON CONFLICT (classroom_id, student_id) DO NOTHING;

-- ==========================================================
-- End Migration 001
-- ==========================================================
